//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HRS.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_HRS_FORM                    101
#define IDD_CUSTOMER_FORM               101
#define IDP_FAILED_OPEN_DATABASE        103
#define IDR_DISPLAYVIEW_TMPL            104
#define IDR_MAINFRAME                   128
#define IDR_HRSTYPE                     129
#define IDR_CUSTOMERTYPE                129
#define IDR_BOXTYPE                     130
#define IDR_BOXMENU                     130
#define IDR_ITEMTYPE                    131
#define IDR_SALETYPE                    132
#define IDR_USERTYPE                    133
#define IDR_COSTTYPE                    134
#define IDD_LOGIN_DLG                   137
#define IDI_ICN_OK                      138
#define IDI_ICN_CANCEL                  139
#define IDD_DLG_NAV                     140
#define IDD_BOX_FORM                    141
#define IDD_ITEM_FORM                   142
#define IDD_SALE_FORM                   143
#define IDD_ITEMLAYOUT_FORM             144
#define IDD_DLG_FIND                    145
#define IDB_BOX                         145
#define IDD_USER_FORM                   146
#define IDB_ITEM                        146
#define IDC_CURSOR_HAND                 146
#define IDB_SALE                        147
#define IDD_MONEY_FORM                  147
#define IDB_USER                        148
#define IDB_MONEY                       149
#define IDB_CUSTOMER                    150
#define IDB_CUSTOMER_IN                 161
#define IDB_BOX_IN                      162
#define IDB_ITEM_IN                     163
#define IDB_MONEY_IN                    164
#define IDB_SALE_IN                     165
#define IDB_USER_IN                     166
#define IDR_MENU_PRINT                  167
#define IDC_STAFF_PIC                   1000
#define IDC_EDT_NAME                    1001
#define IDC_EDT_CUSTOMERNAME            1001
#define IDC_EDT_AGE                     1002
#define IDC_EDT_CUSTOMERAGE             1002
#define IDC_EDT_TITLE                   1003
#define IDC_EDT_CUSTOMERSEX             1003
#define IDC_BTN_ADD                     1004
#define IDC_BTN_MODIFY                  1005
#define IDC_BTN_DEL                     1006
#define IDC_EDT_CUSTOMERTEL             1007
#define IDC_EDT_CUSTOMEREMAIL           1008
#define IDC_EDT_CUSTOMERADDRESS         1009
#define IDC_EDT_CUSTOMERID              1010
#define IDC_EDT_CUSTOMERLVL             1011
#define IDC_EDT_CUSTOMERDES             1012
#define IDC_BTN_CLEAR                   1013
#define IDC_EDT_LOGIN_NAME              1021
#define IDC_EDT_LOGIN_PASSWORD          1022
#define IDC_EDT_SEARCH_BY_NAME          1022
#define IDC_BTN_SEARCH_BY_NAME          1023
#define IDC_BTN_NAV_STAFF               1024
#define IDC_BTN_NAV_CUSTOMER            1024
#define IDC_BTN_NAV_PERF                1025
#define IDC_BTN_UPLOAD_PIC              1025
#define IDC_BTN_NAV_BOX                 1025
#define IDC_BTN_NAV_PROJ                1026
#define IDC_BTN_NAV_ITEM                1026
#define IDC_DATETIMEPICKER_JOINDATE     1026
#define IDC_BTN_NAV_CREATIVE            1027
#define IDC_EDT_BOXID                   1027
#define IDC_DATETIMEPICKER_EXPDTE       1027
#define IDC_BTN_NAV_SALE                1027
#define IDC_EDT_LAYOUT_BOXID            1028
#define IDC_BTN_NAV_USER                1028
#define IDC_EDT_BOXRENTNAME             1028
#define IDC_EDT_BOXPRICE                1029
#define IDC_BTN_NAV_CASH                1029
#define IDC_EDT_BOXDESCRIPTION          1030
#define IDC_BTN_BOXQUERY                1031
#define IDC_EDT_BOXOWNERID              1032
#define IDC_EDT_ITEMPRICE               1032
#define IDC_BTN_BOXCLEAR                1033
#define IDC_EDT_LAYOUT_BOXITEMQTY       1033
#define IDC_EDT_ITEMNAME                1034
#define IDC_EDT_SALEPRICE               1034
#define IDC_BTN_BOXLAYOUT               1034
#define IDC_EDT_USERAGE                 1034
#define IDC_EDT_ITEMID                  1035
#define IDC_EDT_SALEQTY                 1035
#define IDC_BTN_BOXOWNERQUERY           1035
#define IDC_EDT_ITEMOWNERID             1036
#define IDC_EDT_USERADDRESS             1036
#define IDC_BTN_BOXRENTQUERY            1036
#define IDC_BTN_BOXADD                  1037
#define IDC_EDT_ITEMOWNERIDQUERY        1037
#define IDC_BTN_BOXMODIFY               1038
#define IDC_EDT_ITEMIDQUERY             1038
#define IDC_BTN_BOXDEL                  1039
#define IDC_EDT_ITEMQTY                 1040
#define IDC_EDT_USERTEL                 1040
#define IDC_EDT_BOXRENTPRICE            1040
#define IDC_EDT_ITEMDISCNT              1041
#define IDC_EDT_BOXRENTDESCRIPTION      1041
#define IDC_EDT_ITEMTOTPRICE            1042
#define IDC_BTN_BOXRENTADD              1042
#define IDC_DATETIMEPICKER_MANDTE       1043
#define IDC_BTN_BOXRENTMODIFY           1043
#define IDC_EDT_ITEMDESCRIPTION         1044
#define IDC_BTN_BOXRENTDEL              1044
#define IDC_BTN_ITEMADD                 1045
#define IDC_EDT_BOXRENTTOTPRICE         1045
#define IDC_BTN_ITEMMODIFY              1046
#define IDC_BTN_LAYOUT_PUTTOBOX         1046
#define IDC_BTN_BOXRENTOVER             1046
#define IDC_BTN_ITEMDEL                 1047
#define IDC_BTN_LAYOUT_CLEARBOX         1047
#define IDC_BTN_ITEMQUERY               1048
#define IDC_EDT_BOXRENTSEQNUM           1048
#define IDC_BTN_ITEMCLEAR               1049
#define IDC_BTN_ITEMOWNERQUERY          1050
#define IDC_EDT_ITEMINITQTY             1051
#define IDC_EDT_SALEBOXID               1052
#define IDC_BTN_ITEMINFOQUERY           1052
#define IDC_EDT_SALEITEMID              1053
#define IDC_EDT_SALETOTPRICE            1054
#define IDC_EDT_SALEDESCRIPTION         1055
#define IDC_BTN_SALEBOXQUERY            1056
#define IDC_BTN_SALECLEAR               1057
#define IDC_BTN_SALEADD                 1058
#define IDC_BTN_SALEMODIFY              1059
#define IDC_BTN_SALEDEL                 1060
#define IDC_EDT_SALEID                  1061
#define IDC_DATETIMEPICKER_SALEDATE     1062
#define IDC_EDT_BARCODE                 1063
#define IDC_EDT_LAYOUT_BOXTOTPRICE      1064
#define IDC_EDT_SALEITEMNAME            1064
#define IDC_EDT_LAYOUT_ITEMID           1065
#define IDC_BTN_SALEITEMQUERY           1065
#define IDC_EDT_LAYOUT_ITEMOWNERID      1066
#define IDC_BTN_SALETODAYQUERY          1066
#define IDC_EDT_LAYOUT_ITEMNAME         1067
#define IDC_BTN_SALEIDQUERY             1067
#define IDC_EDT_LAYOUT_ITEMPRICE        1068
#define IDC_EDT_SALEBOXIDQUERY          1068
#define IDC_EDT_LAYOUT_ITEMQTY          1069
#define IDC_EDT_SALEITEMIDQUERY         1069
#define IDC_EDT_LAYOUT_ITEMDISCNT       1070
#define IDC_DATETIMEPICKER_SALEDATEFROM 1070
#define IDC_EDT_LAYOUT_ITEMTOTPRICE     1071
#define IDC_DATETIMEPICKER_SALEDATETO   1071
#define IDC_DATETIMEPICKER_LAYOUT_MANDTE 1072
#define IDC_BTN_SALEINFOQUERY           1072
#define IDC_DATETIMEPICKER_LAYOUT_EXPDTE 1073
#define IDC_EDT_LAYOUT_ITEMDESCRIPTION  1074
#define IDC_BTN_LAYOUT_ITEMQUERY        1075
#define IDC_BTN_LAYOUT_ITEMCLEAR        1076
#define IDC_LST_LAYOUT_BOXITEM          1077
#define IDC_LST_CONTENT                 1079
#define IDC_LST_SALERECORD              1081
#define IDC_EDIT_ABOUT                  1082
#define IDC_CHK_ISADMIN                 1083
#define IDC_EDT_USERID                  1084
#define IDC_EDT_USERNAME                1085
#define IDC_EDT_USERSEX                 1086
#define IDC_EDT_USEREMAIL               1087
#define IDC_BTN_USERADD                 1088
#define IDC_BTN_USERMODIFY              1089
#define IDC_BTN_USERDEL                 1090
#define IDC_BTN_USERQUERY               1091
#define IDC_BTN_USERCLEAR               1092
#define IDC_EDT_USERPWD                 1093
#define IDC_STATIC_CUSTOMER             1093
#define IDC_STATIC_BOX                  1094
#define IDC_STATIC_ITEM                 1095
#define IDC_STATIC_SALE                 1096
#define IDC_STATIC_USER                 1097
#define IDC_CHK_CURCUSTOMER             1097
#define IDC_STATIC_MONEY                1098
#define IDC_BTN_CUSTOMER_QUERY          1098
#define IDC_CHK_CUSTOMER_CUSTOMER       1099
#define IDC_CHK_CUSTOMER_BOX            1100
#define IDC_CHK_CUSTOMER_ITEM           1101
#define IDC_CHK_CURBOX                  1102
#define IDC_CHK_BOX_RENT                1103
#define IDC_CHK_BOX_CUSTOMER            1104
#define IDC_CHK_BOX_ITEM                1105
#define IDC_BTN_BOX_QUERY               1106
#define IDC_DTEPK_RENTFROM              1107
#define IDC_DTEPK_RENTTO                1108
#define IDC_CHK_RENTPAYED               1109
#define IDC_CHK_BOX_RENTEXP             1110
#define IDC_CMB_MONEY_CLASS             1112
#define IDC_DTEPK_MONEY_COSTDATE        1113
#define IDC_EDT_MONEY_QTY               1114
#define IDC_EDT_MONEY_DESC              1115
#define IDC_BTN_MONEYADD                1116
#define IDC_BTN_MONEYMODIFY             1117
#define IDC_BTN_MONEYDEL                1118
#define IDC_BTN_MONEYQUERY              1119
#define IDC_BTN_MONEYCLEAR              1120
#define IDC_CMB_MONEY_QUERYCLASS        1121
#define IDC_DTEPK_MONEY_COSTBEGDATE     1122
#define IDC_DTEPK_MONEY_COSTENDDATE     1123
#define IDC_BTN_MONEY_INFOQUERY         1124
#define IDC_EDT_MONEY_COSTER            1125
#define IDC_CHK_QUERYADMIN              1125
#define IDC_EDT_MONEY_COSTID            1126
#define IDC_BTN_QUERYUSER               1126
#define ID_MENU_LOGIN                   32771
#define ID_OPER_NAV                     32772
#define ID_SEPARATOR_EXT                0xE700
#define ID_INDICATOR_ISADMIN            61447
#define ID_INDICATOR_DATE               61448
#define ID_INDICATOR_USER               61449

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1129
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
